dailyfresh/apps/user/urls.py
from django.urls import path
from user.views import RegisterView, index, Login, LogoutUser

app_name = 'user'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    # path('register/', views.register.as_view(), name='register'),
    path('index/', index, name='index'),
    path('login/', Login.as_view(), name='login'),
    path('logout', LogoutUser.as_view(), name='logout'),

]

dailyfresh/dailyfresh/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls'))
    # path('cart/', include('cart.urls')),

]

dailyfresh/apps/cart/models.py
from django.db import models

# Create your models here.

dailyfresh/apps/goods/models.py
from django.db import models

# Create your models here.

dailyfresh/apps/order/models.py
from django.db import models

# Create your models here.

dailyfresh/apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from db.base_model import BaseModel


class User(AbstractUser, BaseModel):
    '''用户模型类'''

    class Meta:
        db_table = 'df_user'
        verbose_name = '用户'
        verbose_name_plural = verbose_name


class Address(BaseModel):
    '''地址模型类'''
    user = models.ForeignKey('User', verbose_name='所属账户', on_delete=None)
    receiver = models.CharField(max_length=20, verbose_name='收件人')
    addr = models.CharField(max_length=256, verbose_name='收件地址')
    phone = models.CharField(max_length=20, verbose_name='联系电话')
    is_default = models.BooleanField(default=False, verbose_name='是否默认')

    class Mate:
        db_table = 'df_address'
        verbose_name = '地址'
        verbose_name_plural = verbose_name

dailyfresh/apps/cart/views.py
from django.shortcuts import render

# Create your views here.

dailyfresh/apps/goods/views.py
from django.shortcuts import render

# Create your views here.

dailyfresh/apps/order/views.py
from django.shortcuts import render

# Create your views here.

dailyfresh/apps/user/views.py
from django.shortcuts import render
from django.http import HttpResponse
import re
from user.models import User
from django.shortcuts import reverse, redirect
from django.views import View
from django.contrib.auth import login, logout, authenticate


# def register(request):
#     '''注册'''
#
#     if request.method == 'GET':
#         '''显示注册页面'''
#
#         return render(request, 'register.html')
#
#     if request.method == 'POST':
#         '''注册处理'''
#
#         # 接收数据
#         username = request.POST.get('username')
#         password = request.POST.get('pwd')
#         email = request.POST.get('email')
#         allow = request.POST.get('allow')
#
#         # 数据校验
#         if not all([username, password, email]):
#             return render(request, 'register.html', {'errmsg': '数据不完整'})
#         # 校验邮箱
#         if not re.match(r'^[a-z0-9][\w.\-]*@[a-z0-9]+(\.[a-z]{2,5}){1,2}$', email):
#             return render(request, 'register.html', {'errmsg': '邮箱格式不正确'})
#         # 是否同意协议
#         if allow != 'on':
#             return render(request, 'register.html', {'errmsg': '请同意协议'})
#         # 校验用户名是否重复
#         try:
#             user = User.objects.get(username=username)
#         except User.DoesNotExist:
#             user = None
#
#         if user:
#             # 用户名已存在
#             return render(request, 'register.html', {'errmsg': '用户名已存在'})
#
#         # 进行业务处理：进行用户注册
#         user = User.objects.create_user(
#             username,
#             email,
#             password
#         )
#         # 返回应答，返回首页
#
#         return redirect(reverse('user:index'))


class RegisterView(View):
    '''注册'''

    def get(self, request):
        '''显示注册页面'''
        return render(request, 'register.html')

    def post(self, request):
        '''进行注册验证'''
        # 接收数据
        username = request.POST.get('username')
        password = request.POST.get('pwd')
        email = request.POST.get('email')
        allow = request.POST.get('allow')

        # 数据校验
        if not all([username, password, email]):
            return render(request, 'register.html', {'errmsg': '数据不完整'})
        # 校验邮箱
        if not re.match(r'^[a-z0-9][\w.\-]*@[a-z0-9]+(\.[a-z]{2,5}){1,2}$', email):
            return render(request, 'register.html', {'errmsg': '邮箱格式不正确'})
        # 是否同意协议
        if allow != 'on':
            return render(request, 'register.html', {'errmsg': '请同意协议'})
        # 校验用户名是否重复
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            user = None

        if user:
            # 用户名已存在
            return render(request, 'register.html', {'errmsg': '用户名已存在'})

        # 进行业务处理：进行用户注册
        user = User.objects.create_user(
            username,
            email,
            password
        )
        # 返回应答，返回首页

        return redirect(reverse('user:login'))


def index(request):
    return render(request, 'index.html')


class Login(View):
    TEMPLATE = 'login.html'

    def get(self, request):

        error = request.GET.get('error', '')

        if 'username' in request.COOKIES:
            username = request.COOKIES['username']
        else:
            username = ''

        return render(request, self.TEMPLATE, {'error': error, 'username': username})

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        remember = request.POST.get('remember')

        exists = User.objects.filter(username=username).exists()
        print(username, password)

        if not exists:
            return redirect('/login?error=没有该用户')

        user = authenticate(username=username, password=password)

        if user:
            login(request, user)
        else:
            return redirect('/login?error=密码错误')

        response = redirect('user:index')
        # 判断是否需要记住用户名
        print(remember)
        print(username)
        if remember == 'on':
            response.set_cookie('username', username, max_age=7*24*3600)

        return response


class LogoutUser(View):

    def get(self, request):

        logout(request)

        return redirect(reverse('user:login'))

dailyfresh/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
</head>
<body>
    <h1>这是首页</h1>
    {% if not user.is_authenticated %}
    <a href="{% url 'user:login' %}">滚去登陆</a>
    {% else %}
    <h2>你tm已经登陆了</h2>
    <a href="{% url 'user:logout' %}">点这里退出登陆</a>
    {% endif %}
</body>
</html>

dailyfresh/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login</title>
    <link rel="stylesheet" href="/static/css/login.css">
</head>
<body>
    {% if not user.is_authenticated %}
    <form class="box" action="{% url 'user:login' %}" method="POST">{% csrf_token %}
        <h1>login</h1>
        <input type="text" name="username"  placeholder="Username">
        <input type="password" name="password"  placeholder="Password">
        <input type="submit" value="Login">
        <a href="#">忘记密码</a>
        <div>{{error}}</div>
        {% else %}
        <a href="{% url 'user:logout' %}">退出登录</a>
        {% endif %}
    </form>
</body>
</html>

dailyfresh/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>register</title>
    <link rel="stylesheet" href="/static/css/register.css">
    <script src="/static/js/jquery-1.12.4.min.js"></script>
</head>
<body>

    <form class="register-form" action="/user/register/" method="post">
        {% csrf_token %}
        <h1>register</h1>

        <div class="txtb">
            <input type="text" placeholder="请输入用户名" name="username" id="username">
            <span ></span>

        </div>
        <div class="txtb">
            <input type="password" name="pwd" id="pwd"  placeholder="请输入密码">
            <span ></span>

        </div>
        <div class="txtb">
            <input type="password" placeholder="请确定密码" name="cpwd" id="cpwd">
            <span ></span>

        </div>
        <div class="txtb">
            <input type="text" name="email" id="email" placeholder="请输入邮箱">
            <span ></span>

        </div>

        <input type="submit" class="logbtn" value="Register">
        <input type="checkbox" name="allow" id="allow">
        <label>同意用户协议</label>
        <span class="error_tip2" ></span><br>
        已有账号？<a href="{% url 'user:login' %}"> 去登陆</a>
    </form>


    <script type="text/javascript">
        $('.txtb input').on('focus', function(){
            $(this).addClass('focus');

        });
        $('.txtb input').on('blur', function(){
            if($(this.val() == ''))
            $(this).addClass('blur');

        });


    </script>


</body>
</html>